threshold: 0.1
threshold_angle: 0.4
# Coordinates are in the North east down frame x -> y and y -> x
wp:
  /px4_1:
    # Circle (not very fluid)
    - { x: 0, y: 1, z: -5, yaw: 0 }
    - { x: 0.7071, y: 0.7071, z: -5, yaw: 0 }
    - { x: 1, y: 0, z: -5, yaw: 0 }
    - { x: 0.7071, y: -0.7071, z: -5, yaw: 0 }
    - { x: 0, y: -1, z: -5, yaw: 0 }
    - { x: -0.7071, y: -0.7071, z: -5, yaw: 0 }
    - { x: -1, y: 0, z: -5, yaw: 0 }
    - { x: -0.7071, y: 0.7071, z: -5, yaw: 0 }
