threshold: 0.1
threshold_angle: 0.9
# Coordinates are in the North east down frame x -> y and y -> x
/px4_1:
    wps:
      # Up and down
      - { x: 0, y: 1, z: -5, yaw: 0 }
      - { x: 0, y: 1, z: -1, yaw: 0 }
    duration: 100.0 # Duration during which the reference is publishing this signal
    
